import psycopg2
from connection import cursor, conn

sql1 = """
        CREATE TABLE herams_colnames (
        id SERIAL,
        long_name VARCHAR(500) UNIQUE,
        short_name VARCHAR(50) UNIQUE,
        PRIMARY KEY (id)
        );
      """
cursor.execute(sql1)
# \copy herams_colnames (long_name, short_name) FROM '/Users/amitprasad/Documents/mali/malidata/database/data/herams_column_names.csv' DELIMITER ',' CSV HEADER

sql2 = """
        CREATE TABLE herams_dbcolnames (
        id SERIAL,
        long_name VARCHAR(500) UNIQUE,
        short_name VARCHAR(50) UNIQUE,
        dbcol_name VARCHAR(50) UNIQUE,
        PRIMARY KEY (id)
        );
      """
cursor.execute(sql2)
# \copy herams_dbcolnames (long_name, short_name, dbcol_name) FROM '/Users/amitprasad/Documents/mali/malidata/database/data/herams_dbcolumn_names.csv' DELIMITER ',' CSV HEADER

sql3 = """
        CREATE TABLE geo6 (
        id SERIAL,
        region_id SMALLINT NOT NULL,
        cercle_id SMALLINT NOT NULL,
        geo6 VARCHAR(100),
        FOREIGN KEY (region_id) REFERENCES region (id),
        FOREIGN KEY (cercle_id) REFERENCES cercle (id),
        PRIMARY KEY (id)
        );
      """
cursor.execute(sql3)
# \copy geo6 (region_id, cercle_id, geo6) FROM '/Users/amitprasad/Documents/mali/malidata/database/data/geo6.csv' DELIMITER ',' CSV HEADER

sql4 = """
        CREATE TABLE herams (
        external_id INT PRIMARY KEY,
        last_synced TIMESTAMP,
        record_date TIMESTAMP,
        region_id SMALLINT NOT NULL,
        cercle_id SMALLINT NOT NULL,
        geo5_id SMALLINT,
        geo5_other VARCHAR(50),
        geo6_id SMALLINT,
        mosd2 VARCHAR(100),
        mosd3 SMALLINT NOT NULL,
        mosd3_other VARCHAR(50),
        mosd4 SMALLINT,
        mosd5 SMALLINT,
        mosdpop INT,
        mosd7 SMALLINT,
        lat FLOAT,
        lon FLOAT,
        condb SMALLINT,
        condbx1 SMALLINT,
        condbx2 SMALLINT,
        condbx3 SMALLINT,
        conde SMALLINT,
        condex1 SMALLINT,
        condex2 SMALLINT,
        condex3 SMALLINT,
        hffunct SMALLINT,
        hffunctx1 SMALLINT,
        hffunctx2 SMALLINT,
        hffunctx3 SMALLINT,
        hfacc SMALLINT,
        hfaccx1 SMALLINT,
        hfaccx2 SMALLINT,
        hfaccx3 SMALLINT,
        hfman SMALLINT,
        hfmanother VARCHAR(50),
        hfsup1 SMALLINT,
        hfsup2 SMALLINT,
        hfsup3_sq1 VARCHAR(100),
        hfsup3_sq2 VARCHAR(100),
        hfsup3_sq3 VARCHAR(100),
        hfsup3_sq4 VARCHAR(100),
        hfsup3_sq5 VARCHAR(100),
        hfsup3_sq6 VARCHAR(100),
        hfsup3_sq7 VARCHAR(100),
        hfsup3_sq8 VARCHAR(100),
        hfsup3_sq9 VARCHAR(100),
        hfsup3_sq10 VARCHAR(100),
        hfsup4_sq1_1 SMALLINT,
        hfsup4_sq1_2 SMALLINT,
        hfsup4_sq1_3 SMALLINT,
        hfsup4_sq1_4 SMALLINT,
        hfsup4_sq1_5 SMALLINT,
        hfsup4_sq1_7 SMALLINT,
        hfsup4_sq2_1 SMALLINT,
        hfsup4_sq2_2 SMALLINT,
        hfsup4_sq2_3 SMALLINT,
        hfsup4_sq2_4 SMALLINT,
        hfsup4_sq2_5 SMALLINT,
        hfsup4_sq2_7 SMALLINT,
        hfsup4_sq3_1 SMALLINT,
        hfsup4_sq3_2 SMALLINT,
        hfsup4_sq3_3 SMALLINT,
        hfsup4_sq3_4 SMALLINT,
        hfsup4_sq3_5 SMALLINT,
        hfsup4_sq3_7 SMALLINT,
        hfsup4_sq4_1 SMALLINT,
        hfsup4_sq4_2 SMALLINT,
        hfsup4_sq4_3 SMALLINT,
        hfsup4_sq4_4 SMALLINT,
        hfsup4_sq4_5 SMALLINT,
        hfsup4_sq4_7 SMALLINT,
        hfsup4_sq5_1 SMALLINT,
        hfsup4_sq5_2 SMALLINT,
        hfsup4_sq5_3 SMALLINT,
        hfsup4_sq5_4 SMALLINT,
        hfsup4_sq5_5 SMALLINT,
        hfsup4_sq5_7 SMALLINT,
        hfsup4_sq6_1 SMALLINT,
        hfsup4_sq6_2 SMALLINT,
        hfsup4_sq6_3 SMALLINT,
        hfsup4_sq6_4 SMALLINT,
        hfsup4_sq6_5 SMALLINT,
        hfsup4_sq6_7 SMALLINT,
        hfsup4_sq7_1 SMALLINT,
        hfsup4_sq7_2 SMALLINT,
        hfsup4_sq7_3 SMALLINT,
        hfsup4_sq7_4 SMALLINT,
        hfsup4_sq7_5 SMALLINT,
        hfsup4_sq7_7 SMALLINT,
        hfsup4_sq8_1 SMALLINT,
        hfsup4_sq8_2 SMALLINT,
        hfsup4_sq8_3 SMALLINT,
        hfsup4_sq8_4 SMALLINT,
        hfsup4_sq8_5 SMALLINT,
        hfsup4_sq8_7 SMALLINT,
        hfsup4_sq9_1 SMALLINT,
        hfsup4_sq9_2 SMALLINT,
        hfsup4_sq9_3 SMALLINT,
        hfsup4_sq9_4 SMALLINT,
        hfsup4_sq9_5 SMALLINT,
        hfsup4_sq9_7 SMALLINT,
        hfsup4_sq10_1 SMALLINT,
        hfsup4_sq10_2 SMALLINT,
        hfsup4_sq10_3 SMALLINT,
        hfsup4_sq10_4 SMALLINT,
        hfsup4_sq10_5 SMALLINT,
        hfsup4_sq10_7 SMALLINT,
        hfinp1 INT,
        bawa1 SMALLINT,
        bawa1x1 SMALLINT,
        bawa1x2 SMALLINT,
        bawa1x3 SMALLINT,
        basa1 SMALLINT,
        basa1x1 SMALLINT,
        basa1x2 SMALLINT,
        basa1x3 SMALLINT,
        bawm1 SMALLINT,
        bawm2 SMALLINT,
        bawm2x1 SMALLINT,
        bawm2x2 SMALLINT,
        bawm2x3 SMALLINT,
        bawm3 SMALLINT,
        bawm3x1 SMALLINT,
        bawm3x2 SMALLINT,
        bawm3x3 SMALLINT,
        baen1 SMALLINT,
        baen1x1 SMALLINT,
        baen1x2 SMALLINT,
        baen1x3 SMALLINT,
        baco1 SMALLINT,
        baco1x1 SMALLINT,
        baco1x2 SMALLINT,
        baco1x3 SMALLINT,
        bacc1 SMALLINT,
        bacc1x1 SMALLINT,
        bacc1x2 SMALLINT,
        bacc1x3 SMALLINT,
        info1 SMALLINT,
        info1x SMALLINT,
        info2 SMALLINT,
        info2x SMALLINT,
        info3 SMALLINT,
        info3x SMALLINT,
        qhe100 SMALLINT,
        qhe100x1 SMALLINT,
        qhe100x2 SMALLINT,
        qhe100x3 SMALLINT,
        qhe101 SMALLINT,
        qhe101x1 SMALLINT,
        qhe101x2 SMALLINT,
        qhe101x3 SMALLINT,
        qhe102 SMALLINT,
        qhe102x1 SMALLINT,
        qhe102x2 SMALLINT,
        qhe102x3 SMALLINT,
        qhe103 SMALLINT,
        qhe103x1 SMALLINT,
        qhe103x2 SMALLINT,
        qhe103x3 SMALLINT,
        qhe104 SMALLINT,
        qhe104x1 SMALLINT,
        qhe104x2 SMALLINT,
        qhe104x3 SMALLINT,
        qhe105 SMALLINT,
        qhe105x1 SMALLINT,
        qhe105x2 SMALLINT,
        qhe105x3 SMALLINT,
        qhe106 SMALLINT,
        qhe106x1 SMALLINT,
        qhe106x2 SMALLINT,
        qhe106x3 SMALLINT,
        qhe107 SMALLINT,
        qhe107x1 SMALLINT,
        qhe107x2 SMALLINT,
        qhe107x3 SMALLINT,
        qhe108 SMALLINT,
        qhe108x1 SMALLINT,
        qhe108x2 SMALLINT,
        qhe108x3 SMALLINT,
        qhe109 SMALLINT,
        qhe109x1 SMALLINT,
        qhe109x2 SMALLINT,
        qhe109x3 SMALLINT,
        qhe110 SMALLINT,
        qhe110x1 SMALLINT,
        qhe110x2 SMALLINT,
        qhe110x3 SMALLINT,
        qhe111 SMALLINT,
        qhe111x1 SMALLINT,
        qhe111x2 SMALLINT,
        qhe111x3 SMALLINT,
        qhe112 SMALLINT,
        qhe112x1 SMALLINT,
        qhe112x2 SMALLINT,
        qhe112x3 SMALLINT,
        qhe113 SMALLINT,
        qhe113x1 SMALLINT,
        qhe113x2 SMALLINT,
        qhe113x3 SMALLINT,
        qhe114 SMALLINT,
        qhe114x1 SMALLINT,
        qhe114x2 SMALLINT,
        qhe114x3 SMALLINT,
        qhe115 SMALLINT,
        qhe115x1 SMALLINT,
        qhe115x2 SMALLINT,
        qhe115x3 SMALLINT,
        qhe116 SMALLINT,
        qhe116x1 SMALLINT,
        qhe116x2 SMALLINT,
        qhe116x3 SMALLINT,
        qhe117 SMALLINT,
        qhe117x1 SMALLINT,
        qhe117x2 SMALLINT,
        qhe117x3 SMALLINT,
        qhe118 SMALLINT,
        qhe118x1 SMALLINT,
        qhe118x2 SMALLINT,
        qhe118x3 SMALLINT,
        qhe119 SMALLINT,
        qhe119x1 SMALLINT,
        qhe119x2 SMALLINT,
        qhe119x3 SMALLINT,
        qhe120 SMALLINT,
        qhe120x1 SMALLINT,
        qhe120x2 SMALLINT,
        qhe120x3 SMALLINT,
        qhe121 SMALLINT,
        qhe121x1 SMALLINT,
        qhe121x2 SMALLINT,
        qhe121x3 SMALLINT,
        qhe122 SMALLINT,
        qhe122x1 SMALLINT,
        qhe122x2 SMALLINT,
        qhe122x3 SMALLINT,
        qhe123 SMALLINT,
        qhe123x1 SMALLINT,
        qhe123x2 SMALLINT,
        qhe123x3 SMALLINT,
        qhe124 SMALLINT,
        qhe124x1 SMALLINT,
        qhe124x2 SMALLINT,
        qhe124x3 SMALLINT,
        qhe125 SMALLINT,
        qhe125x1 SMALLINT,
        qhe125x2 SMALLINT,
        qhe125x3 SMALLINT,
        qhe200 SMALLINT,
        qhe200x1 SMALLINT,
        qhe200x2 SMALLINT,
        qhe200x3 SMALLINT,
        qhe201 SMALLINT,
        qhe201x1 SMALLINT,
        qhe201x2 SMALLINT,
        qhe201x3 SMALLINT,
        qhe202 SMALLINT,
        qhe202x1 SMALLINT,
        qhe202x2 SMALLINT,
        qhe202x3 SMALLINT,
        qhe203 SMALLINT,
        qhe203x1 SMALLINT,
        qhe203x2 SMALLINT,
        qhe203x3 SMALLINT,
        qhe204 SMALLINT,
        qhe204x1 SMALLINT,
        qhe204x2 SMALLINT,
        qhe204x3 SMALLINT,
        qhe205 SMALLINT,
        qhe205x1 SMALLINT,
        qhe205x2 SMALLINT,
        qhe205x3 SMALLINT,
        qhe206 SMALLINT,
        qhe206x1 SMALLINT,
        qhe206x2 SMALLINT,
        qhe206x3 SMALLINT,
        qhe207 SMALLINT,
        qhe207x1 SMALLINT,
        qhe207x2 SMALLINT,
        qhe207x3 SMALLINT,
        qhe208 SMALLINT,
        qhe208x1 SMALLINT,
        qhe208x2 SMALLINT,
        qhe208x3 SMALLINT,
        qhe209 SMALLINT,
        qhe209x1 SMALLINT,
        qhe209x2 SMALLINT,
        qhe209x3 SMALLINT,
        qhe210 SMALLINT,
        qhe210x1 SMALLINT,
        qhe210x2 SMALLINT,
        qhe210x3 SMALLINT,
        qhe211 SMALLINT,
        qhe211x1 SMALLINT,
        qhe211x2 SMALLINT,
        qhe211x3 SMALLINT,
        qhe301 SMALLINT,
        qhe301x1 SMALLINT,
        qhe301x2 SMALLINT,
        qhe301x3 SMALLINT,
        qhe302 SMALLINT,
        qhe302x1 SMALLINT,
        qhe302x2 SMALLINT,
        qhe302x3 SMALLINT,
        qhe303 SMALLINT,
        qhe303x1 SMALLINT,
        qhe303x2 SMALLINT,
        qhe303x3 SMALLINT,
        qhe304 SMALLINT,
        qhe304x1 SMALLINT,
        qhe304x2 SMALLINT,
        qhe304x3 SMALLINT,
        qhe305 SMALLINT,
        qhe305x1 SMALLINT,
        qhe305x2 SMALLINT,
        qhe305x3 SMALLINT,
        qhe306 SMALLINT,
        qhe306x1 SMALLINT,
        qhe306x2 SMALLINT,
        qhe306x3 SMALLINT,
        qhe307 SMALLINT,
        qhe307x1 SMALLINT,
        qhe307x2 SMALLINT,
        qhe307x3 SMALLINT,
        qhe308 SMALLINT,
        qhe308x1 SMALLINT,
        qhe308x2 SMALLINT,
        qhe308x3 SMALLINT,
        qhe309 SMALLINT,
        qhe309x1 SMALLINT,
        qhe309x2 SMALLINT,
        qhe309x3 SMALLINT,
        qhe310 SMALLINT,
        qhe310x1 SMALLINT,
        qhe310x2 SMALLINT,
        qhe310x3 SMALLINT,
        qhe311 SMALLINT,
        qhe311x1 SMALLINT,
        qhe311x2 SMALLINT,
        qhe311x3 SMALLINT,
        qhe411 SMALLINT,
        qhe412 SMALLINT,
        qhe412x1 SMALLINT,
        qhe412x2 SMALLINT,
        qhe412x3 SMALLINT,
        qhe413 SMALLINT,
        qhe413x1 SMALLINT,
        qhe413x2 SMALLINT,
        qhe413x3 SMALLINT,
        qhe414 SMALLINT,
        qhe414x1 SMALLINT,
        qhe414x2 SMALLINT,
        qhe414x3 SMALLINT,
        qhe415 SMALLINT,
        qhe415x1 SMALLINT,
        qhe415x2 SMALLINT,
        qhe415x3 SMALLINT,
        qhe416 SMALLINT,
        qhe416x1 SMALLINT,
        qhe416x2 SMALLINT,
        qhe416x3 SMALLINT,
        qhe417 SMALLINT,
        qhe417x1 SMALLINT,
        qhe417x2 SMALLINT,
        qhe417x3 SMALLINT,
        qhe418 SMALLINT,
        qhe418x1 SMALLINT,
        qhe418x2 SMALLINT,
        qhe418x3 SMALLINT,
        qhe421 SMALLINT,
        qhe421x1 SMALLINT,
        qhe421x2 SMALLINT,
        qhe421x3 SMALLINT,
        qhe422 SMALLINT,
        qhe422x1 SMALLINT,
        qhe422x2 SMALLINT,
        qhe422x3 SMALLINT,
        qhe423 SMALLINT,
        qhe423x1 SMALLINT,
        qhe423x2 SMALLINT,
        qhe423x3 SMALLINT,
        qhe424 SMALLINT,
        qhe424x1 SMALLINT,
        qhe424x2 SMALLINT,
        qhe424x3 SMALLINT,
        qhe425 SMALLINT,
        qhe425x1 SMALLINT,
        qhe425x2 SMALLINT,
        qhe425x3 SMALLINT,
        qhe426 SMALLINT,
        qhe426x1 SMALLINT,
        qhe426x2 SMALLINT,
        qhe426x3 SMALLINT,
        qhe427 SMALLINT,
        qhe427x1 SMALLINT,
        qhe427x2 SMALLINT,
        qhe427x3 SMALLINT,
        qhe428 SMALLINT,
        qhe428x1 SMALLINT,
        qhe428x2 SMALLINT,
        qhe428x3 SMALLINT,
        qhe431 SMALLINT,
        qhe431x1 SMALLINT,
        qhe431x2 SMALLINT,
        qhe431x3 SMALLINT,
        qhe432 SMALLINT,
        qhe432x1 SMALLINT,
        qhe432x2 SMALLINT,
        qhe432x3 SMALLINT,
        qhe433 SMALLINT,
        qhe433x1 SMALLINT,
        qhe433x2 SMALLINT,
        qhe433x3 SMALLINT,
        qhe501 SMALLINT,
        qhe501x1 SMALLINT,
        qhe501x2 SMALLINT,
        qhe501x3 SMALLINT,
        qhe502 SMALLINT,
        qhe502x1 SMALLINT,
        qhe502x2 SMALLINT,
        qhe502x3 SMALLINT,
        qhe503 SMALLINT,
        qhe503x1 SMALLINT,
        qhe503x2 SMALLINT,
        qhe503x3 SMALLINT,
        qhe504 SMALLINT,
        qhe504x1 SMALLINT,
        qhe504x2 SMALLINT,
        qhe504x3 SMALLINT,
        qhe505 SMALLINT,
        qhe505x1 SMALLINT,
        qhe505x2 SMALLINT,
        qhe505x3 SMALLINT,
        qhe506 SMALLINT,
        qhe506x1 SMALLINT,
        qhe506x2 SMALLINT,
        qhe506x3 SMALLINT,
        qhe507 SMALLINT,
        qhe507x1 SMALLINT,
        qhe507x2 SMALLINT,
        qhe507x3 SMALLINT,
        qhe508 SMALLINT,
        qhe508x1 SMALLINT,
        qhe508x2 SMALLINT,
        qhe508x3 SMALLINT,
        qhe509 SMALLINT,
        qhe509x1 SMALLINT,
        qhe509x2 SMALLINT,
        qhe509x3 SMALLINT,
        qhe510 SMALLINT,
        qhe510x1 SMALLINT,
        qhe510x2 SMALLINT,
        qhe510x3 SMALLINT,
        qhe511 SMALLINT,
        qhe511x1 SMALLINT,
        qhe511x2 SMALLINT,
        qhe511x3 SMALLINT,
        qhe512 SMALLINT,
        qhe512x1 SMALLINT,
        qhe512x2 SMALLINT,
        qhe512x3 SMALLINT,
        qhe513 SMALLINT,
        qhe513x1 SMALLINT,
        qhe513x2 SMALLINT,
        qhe513x3 SMALLINT,
        FOREIGN KEY (region_id) REFERENCES region (id),
        FOREIGN KEY (cercle_id) REFERENCES cercle (id),
        FOREIGN KEY (geo5_id) REFERENCES geo5 (id),
        FOREIGN KEY (geo6_id) REFERENCES geo6 (id),
        FOREIGN KEY (mosd3) REFERENCES mosd3 (id),
        FOREIGN KEY (mosd4) REFERENCES mosd4 (id),
        FOREIGN KEY (mosd5) REFERENCES mosd5 (id),
        FOREIGN KEY (mosd7) REFERENCES mosd7 (id),
        FOREIGN KEY (condb) REFERENCES condb (id),
        FOREIGN KEY (condbx1) REFERENCES condbx (id),
        FOREIGN KEY (condbx2) REFERENCES condbx (id),
        FOREIGN KEY (condbx3) REFERENCES condbx (id),
        FOREIGN KEY (conde) REFERENCES condb (id),
        FOREIGN KEY (condex1) REFERENCES condbx (id),
        FOREIGN KEY (condex2) REFERENCES condbx (id),
        FOREIGN KEY (condex3) REFERENCES condbx (id),
        FOREIGN KEY (hffunct) REFERENCES hffunct (id),
        FOREIGN KEY (hffunctx1) REFERENCES hffunctx (id),
        FOREIGN KEY (hffunctx2) REFERENCES hffunctx (id),
        FOREIGN KEY (hffunctx3) REFERENCES hffunctx (id),
        FOREIGN KEY (hfacc) REFERENCES hfacc (id),
        FOREIGN KEY (hfaccx1) REFERENCES hfaccx (id),
        FOREIGN KEY (hfaccx2) REFERENCES hfaccx (id),
        FOREIGN KEY (hfaccx3) REFERENCES hfaccx (id),
        FOREIGN KEY (hfman) REFERENCES hfman (id),
        FOREIGN KEY (hfsup1) REFERENCES hfsup1 (id),
        FOREIGN KEY (bawa1) REFERENCES hfinp1 (id),
        FOREIGN KEY (bawa1x1) REFERENCES bawa1x (id),
        FOREIGN KEY (bawa1x2) REFERENCES bawa1x (id),
        FOREIGN KEY (bawa1x3) REFERENCES bawa1x (id),
        FOREIGN KEY (basa1) REFERENCES hfinp1 (id),
        FOREIGN KEY (basa1x1) REFERENCES basa1x (id),
        FOREIGN KEY (basa1x2) REFERENCES basa1x (id),
        FOREIGN KEY (basa1x3) REFERENCES basa1x (id),
        FOREIGN KEY (bawm1) REFERENCES hfinp1 (id),
        FOREIGN KEY (bawm2) REFERENCES hfinp1 (id),
        FOREIGN KEY (bawm2x1) REFERENCES bawm2x (id),
        FOREIGN KEY (bawm2x2) REFERENCES bawm2x (id),
        FOREIGN KEY (bawm2x3) REFERENCES bawm2x (id),
        FOREIGN KEY (bawm3) REFERENCES hfinp1 (id),
        FOREIGN KEY (bawm3x1) REFERENCES bawm2x (id),
        FOREIGN KEY (bawm3x2) REFERENCES bawm2x (id),
        FOREIGN KEY (bawm3x3) REFERENCES bawm2x (id),
        FOREIGN KEY (baen1) REFERENCES hfinp1 (id),
        FOREIGN KEY (baen1x1) REFERENCES baen1x (id),
        FOREIGN KEY (baen1x2) REFERENCES baen1x (id),
        FOREIGN KEY (baen1x3) REFERENCES baen1x (id),
        FOREIGN KEY (baco1) REFERENCES hfinp1 (id),
        FOREIGN KEY (baco1x1) REFERENCES baco1x (id),
        FOREIGN KEY (baco1x2) REFERENCES baco1x (id),
        FOREIGN KEY (baco1x3) REFERENCES baco1x (id),
        FOREIGN KEY (bacc1) REFERENCES hfinp1 (id),
        FOREIGN KEY (bacc1x1) REFERENCES baen1x (id),
        FOREIGN KEY (bacc1x2) REFERENCES baen1x (id),
        FOREIGN KEY (bacc1x3) REFERENCES baen1x (id),
        FOREIGN KEY (info1) REFERENCES triage1 (id),
        FOREIGN KEY (info1x) REFERENCES info1x (id),
        FOREIGN KEY (info2) REFERENCES triage1 (id),
        FOREIGN KEY (info2x) REFERENCES info1x (id),
        FOREIGN KEY (info3) REFERENCES triage1 (id),
        FOREIGN KEY (info3x) REFERENCES info1x (id),
        FOREIGN KEY (qhe100) REFERENCES triage1 (id),
        FOREIGN KEY (qhe100x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe100x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe100x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe101) REFERENCES triage1 (id),
        FOREIGN KEY (qhe101x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe101x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe101x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe102) REFERENCES triage1 (id),
        FOREIGN KEY (qhe102x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe102x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe102x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe103) REFERENCES triage1 (id),
        FOREIGN KEY (qhe103x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe103x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe103x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe104) REFERENCES triage1 (id),
        FOREIGN KEY (qhe104x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe104x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe104x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe105) REFERENCES triage1 (id),
        FOREIGN KEY (qhe105x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe105x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe105x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe106) REFERENCES triage1 (id),
        FOREIGN KEY (qhe106x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe106x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe106x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe107) REFERENCES triage1 (id),
        FOREIGN KEY (qhe107x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe107x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe107x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe108) REFERENCES triage1 (id),
        FOREIGN KEY (qhe108x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe108x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe108x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe109) REFERENCES triage1 (id),
        FOREIGN KEY (qhe109x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe109x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe109x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe110) REFERENCES triage1 (id),
        FOREIGN KEY (qhe110x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe110x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe110x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe111) REFERENCES triage1 (id),
        FOREIGN KEY (qhe111x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe111x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe111x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe112) REFERENCES triage1 (id),
        FOREIGN KEY (qhe112x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe112x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe112x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe113) REFERENCES triage1 (id),
        FOREIGN KEY (qhe113x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe113x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe113x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe114) REFERENCES triage1 (id),
        FOREIGN KEY (qhe114x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe114x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe114x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe115) REFERENCES triage1 (id),
        FOREIGN KEY (qhe115x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe115x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe115x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe116) REFERENCES triage1 (id),
        FOREIGN KEY (qhe116x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe116x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe116x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe117) REFERENCES triage1 (id),
        FOREIGN KEY (qhe117x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe117x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe117x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe118) REFERENCES triage1 (id),
        FOREIGN KEY (qhe118x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe118x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe118x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe119) REFERENCES triage1 (id),
        FOREIGN KEY (qhe119x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe119x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe119x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe120) REFERENCES triage1 (id),
        FOREIGN KEY (qhe120x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe120x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe120x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe121) REFERENCES triage1 (id),
        FOREIGN KEY (qhe121x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe121x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe121x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe122) REFERENCES triage1 (id),
        FOREIGN KEY (qhe122x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe122x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe122x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe123) REFERENCES triage1 (id),
        FOREIGN KEY (qhe123x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe123x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe123x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe124) REFERENCES triage1 (id),
        FOREIGN KEY (qhe124x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe124x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe124x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe125) REFERENCES triage1 (id),
        FOREIGN KEY (qhe125x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe125x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe125x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe200) REFERENCES triage1 (id),
        FOREIGN KEY (qhe200x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe200x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe200x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe201) REFERENCES triage1 (id),
        FOREIGN KEY (qhe201x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe201x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe201x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe202) REFERENCES triage1 (id),
        FOREIGN KEY (qhe202x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe202x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe202x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe203) REFERENCES triage1 (id),
        FOREIGN KEY (qhe203x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe203x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe203x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe204) REFERENCES triage1 (id),
        FOREIGN KEY (qhe204x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe204x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe204x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe205) REFERENCES triage1 (id),
        FOREIGN KEY (qhe205x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe205x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe205x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe206) REFERENCES triage1 (id),
        FOREIGN KEY (qhe206x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe206x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe206x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe207) REFERENCES triage1 (id),
        FOREIGN KEY (qhe207x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe207x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe207x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe208) REFERENCES triage1 (id),
        FOREIGN KEY (qhe208x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe208x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe208x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe209) REFERENCES triage1 (id),
        FOREIGN KEY (qhe209x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe209x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe209x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe210) REFERENCES triage1 (id),
        FOREIGN KEY (qhe210x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe210x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe210x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe211) REFERENCES triage1 (id),
        FOREIGN KEY (qhe211x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe211x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe211x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe301) REFERENCES triage1 (id),
        FOREIGN KEY (qhe301x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe301x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe301x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe302) REFERENCES triage1 (id),
        FOREIGN KEY (qhe302x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe302x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe302x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe303) REFERENCES triage1 (id),
        FOREIGN KEY (qhe303x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe303x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe303x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe304) REFERENCES triage1 (id),
        FOREIGN KEY (qhe304x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe304x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe304x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe305) REFERENCES triage1 (id),
        FOREIGN KEY (qhe305x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe305x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe305x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe306) REFERENCES triage1 (id),
        FOREIGN KEY (qhe306x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe306x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe306x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe307) REFERENCES triage1 (id),
        FOREIGN KEY (qhe307x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe307x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe307x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe308) REFERENCES triage1 (id),
        FOREIGN KEY (qhe308x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe308x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe308x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe309) REFERENCES triage1 (id),
        FOREIGN KEY (qhe309x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe309x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe309x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe310) REFERENCES triage1 (id),
        FOREIGN KEY (qhe310x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe310x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe310x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe311) REFERENCES triage1 (id),
        FOREIGN KEY (qhe311x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe311x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe311x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe411) REFERENCES triage1 (id),
        FOREIGN KEY (qhe412) REFERENCES triage1 (id),
        FOREIGN KEY (qhe412x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe412x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe412x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe413) REFERENCES triage1 (id),
        FOREIGN KEY (qhe413x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe413x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe413x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe414) REFERENCES triage1 (id),
        FOREIGN KEY (qhe414x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe414x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe414x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe415) REFERENCES triage1 (id),
        FOREIGN KEY (qhe415x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe415x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe415x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe416) REFERENCES triage1 (id),
        FOREIGN KEY (qhe416x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe416x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe416x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe417) REFERENCES triage1 (id),
        FOREIGN KEY (qhe417x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe417x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe417x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe418) REFERENCES triage1 (id),
        FOREIGN KEY (qhe418x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe418x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe418x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe421) REFERENCES triage1 (id),
        FOREIGN KEY (qhe421x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe421x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe421x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe422) REFERENCES triage1 (id),
        FOREIGN KEY (qhe422x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe422x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe422x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe423) REFERENCES triage1 (id),
        FOREIGN KEY (qhe423x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe423x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe423x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe424) REFERENCES triage1 (id),
        FOREIGN KEY (qhe424x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe424x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe424x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe425) REFERENCES triage1 (id),
        FOREIGN KEY (qhe425x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe425x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe425x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe426) REFERENCES triage1 (id),
        FOREIGN KEY (qhe426x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe426x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe426x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe427) REFERENCES triage1 (id),
        FOREIGN KEY (qhe427x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe427x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe427x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe428) REFERENCES triage1 (id),
        FOREIGN KEY (qhe428x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe428x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe428x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe431) REFERENCES triage1 (id),
        FOREIGN KEY (qhe431x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe431x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe431x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe432) REFERENCES triage1 (id),
        FOREIGN KEY (qhe432x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe432x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe432x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe433) REFERENCES triage1 (id),
        FOREIGN KEY (qhe433x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe433x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe433x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe501) REFERENCES triage1 (id),
        FOREIGN KEY (qhe501x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe501x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe501x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe502) REFERENCES triage1 (id),
        FOREIGN KEY (qhe502x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe502x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe502x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe503) REFERENCES triage1 (id),
        FOREIGN KEY (qhe503x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe503x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe503x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe504) REFERENCES triage1 (id),
        FOREIGN KEY (qhe504x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe504x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe504x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe505) REFERENCES triage1 (id),
        FOREIGN KEY (qhe505x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe505x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe505x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe506) REFERENCES triage1 (id),
        FOREIGN KEY (qhe506x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe506x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe506x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe507) REFERENCES triage1 (id),
        FOREIGN KEY (qhe507x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe507x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe507x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe508) REFERENCES triage1 (id),
        FOREIGN KEY (qhe508x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe508x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe508x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe509) REFERENCES triage1 (id),
        FOREIGN KEY (qhe509x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe509x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe509x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe510) REFERENCES triage1 (id),
        FOREIGN KEY (qhe510x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe510x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe510x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe511) REFERENCES triage1 (id),
        FOREIGN KEY (qhe511x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe511x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe511x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe512) REFERENCES triage1 (id),
        FOREIGN KEY (qhe512x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe512x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe512x3) REFERENCES lab1x (id),
        FOREIGN KEY (qhe513) REFERENCES triage1 (id),
        FOREIGN KEY (qhe513x1) REFERENCES lab1x (id),
        FOREIGN KEY (qhe513x2) REFERENCES lab1x (id),
        FOREIGN KEY (qhe513x3) REFERENCES lab1x (id)
        );
      """
cursor.execute(sql3)
# \copy herams FROM '/Users/amitprasad/Documents/mali/malidata/database/data/HeRAMS_Mali_Normalized.csv' DELIMITER ',' CSV HEADER